### ISSUE TITLE
payload order not working

### ISSUE THREAD

**Issue by bethsecor** [ToniRib/traffic-spy#64]
line 11: order(count: :desc) is not the same every time. I think we need to sort by with ruby by descending value and then by the key so we get the same result every time.

**Comment by ToniRib** [comment]
sounds fine to me, I'm going to look at your payload testing branch

**Comment by ToniRib** [comment]
Yeah, it looks like the sort by descending order is fine BUT there's issues when two items have the same count. I assume you mean sort by descending value, then resort ties by key alphabetically?
